openapi: 3.0.1

info:
  title: Notes Manager
  description: A REST API which enables CRUD operations to be performed on notes consisting of a title and description.
  contact:
    name: turnerdaniel
    url: 'https://www.github.com/turnerdaniel'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/turnerdaniel/notes-manager/main/LICENSE.md'
  version: 1.2.0

#servers:
#  - url: 'http://localhost:8080/v1'

paths:
  '/v1/notes/{id}':
    parameters:
      - name: id
        in: path
        description: Unique value used to identify each note
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - Note Controller
      operationId: getNoteById
      responses:
        '200':
          description: Note has been found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
              example:
                id: 1
                title: Reminder
                description: Visit the hospital for doctors appointment.
                createdAt: '2021-04-10T12:30:47.583Z'
                updatedAt: '2021-04-10T12:30:47.583Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Note Controller
      operationId: updateNoteById
      requestBody:
        $ref: '#/components/requestBodies/Note'
      responses:
        '200':
          description: Note has been updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
              example:
                id: 1
                title: Reminder
                description: Visit the hospital for doctors appointment.
                createdAt: '2021-04-10T12:30:47.583Z'
                updatedAt: '2021-04-11T14:45:12.856Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Note Controller
      operationId: deleteNoteById
      responses:
        '204':
          description: Note has been deleted.
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/notes:
    get:
      tags:
        - Note Controller
      operationId: getAllNotes
      responses:
        '200':
          description: Notes have been found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
                example:
                  - id: 1
                    title: Reminder
                    description: Visit the hospital for doctors appointment.
                    createdAt: '2021-04-10T12:30:47.583Z'
                    updatedAt: '2021-04-11T14:45:12.856Z'
                  - id: 2
                    title: Chore
                    description: Clean up room.
                    createdAt: '2021-04-11T10:00:32.342Z'
                    updatedAt: '2021-04-11T10:00:32.342Z'

    post:
      tags:
        - Note Controller
      operationId: createNote
      requestBody:
        $ref: '#/components/requestBodies/Note'
      responses:
        '201':
          description: Note has been created.
          headers:
            Location:
              description: Indicates the URL to redirect a page to.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
              example:
                id: 1
                title: Reminder
                description: Visit the hospital for doctors appointment.
                createdAt: '2021-04-10T12:30:47.583Z'
                updatedAt: '2021-04-10T12:30:47.583Z'


components:
  requestBodies:
    Note:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Note'
          example:
            title: Reminder
            description: Visit the hospital for doctors appointment.

  responses:
    BadRequest:
      description: Provided `id` is not valid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            timestamp: '2021-04-10T12:30:47.583Z'
            status: 400
            error: Bad Request
            message: ''
            path: /v1/notes/abcd
    NotFound:
      description: Note with specified `id` not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            timestamp: '2021-04-10T12:30:47.583Z'
            status: 404
            error: Not Found
            message: ''
            path: /v1/notes/201

  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Unique value used to identify each note
        title:
          type: string
          description: Title of the note
        description:
          type: string
          description: Description of the note
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: The time the note was created in ISO-8601 format
        updatedAt:
          type: string
          format: date-time
          readOnly: true
          description: The time the note was last updated in ISO-8601 format
    Error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: The time the error occured in ISO-8601 format
        status:
          type: integer
          description: The HTTP status code
        error:
          type: string
          description: The name of the HTTP status code
        message:
          type: string
          description: Additional information about the error
        path:
          type: string
          description: The URI where the error occured
