
name: Gradle CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/coverage.xml
          flags: unittests

  deploy:
    name: Deployment
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Get current project version
        run: echo 'PROJECT_VER='&`./gradlew -q version` >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: $PROJECT_VER
          release_name: $PROJECT_VER
          draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#        Download artefact and upload to Release...
